### ISSUE TITLE
如何增加自己的打字练习的文本材料？

### ISSUE THREAD

**Issue by Sunlly0** [myth984/doubl-spell#6]
刚学双拼发现了这个宝藏项目！很有用！
想请教一下作者，如果想自己增加一些打字练习的文本材料，怎么加呢？

**Comment by myth984** [comment]
如果你懂代码的话
可以修改这里 https://github.com/myth984/double-spell/blob/777b1796bea87233ddbe18b3341f9b0008e97e46/src/components/Main.vue#L126
